# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "News"
#  url = "#posts"
#  weight = 20

[[main]]
  name = "Projects"
  url = "#"
  weight = 10

[[main]]
  name = "supersmartR"
  parent = "Projects"
  url = "/projects#supersmartr"
  weight = 60

[[main]]
  name = "Living fossils?"
  parent = "Projects"
  url = "/projects#livingfossils"
  weight = 80

[[main]]
  name = "Software"
  url = "/software"
  weight = 100

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 120

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 50

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "files/CV.pdf"
